home.nono.io doesn't need an IPv6 address
...at least not for connecting to -- who wants to connect
to an Apple Airport?

With IPv6 we connect directly to the machine; we don't use
home.nono.io + port forwarding.

fixes:
```
ValueError: home.nono.io challenge did not pass: {u'status': u'invalid', u'validationRecord': [{u'addressesResolved': [u'73.15.134.22', u'2001:558:6045:109:5de4:77ef:a6f1:4895'], u'url': u'http://home.nono.io/.well-known/acme-challenge/EZU9XimkVk2dCoLIf_tXyvfgT24tM_eAVQQkxBrP-oM', u'hostname': u'home.nono.io', u'addressesTried': [], u'addressUsed': u'2001:558:6045:109:5de4:77ef:a6f1:4895', u'port': u'80'}], u'keyAuthorization': u'EZU9XimkVk2dCoLIf_tXyvfgT24tM_eAVQQkxBrP-oM.XGsQQVTYFsJwrYIFCoUbfU_Z3U7DxVrsHLaVyryKgoc', u'uri': u'https://acme-v01.api.letsencrypt.org/acme/challenge/j8cdEBROGiOuB6Y35jY9hIC6UPADEc31pRdQfzqLDfA/1799070096', u'token': u'EZU9XimkVk2dCoLIf_tXyvfgT24tM_eAVQQkxBrP-oM', u'error': {u'status': 400, u'type': u'urn:acme:error:connection', u'detail': u'Fetching http://home.nono.io/.well-known/acme-challenge/EZU9XimkVk2dCoLIf_tXyvfgT24tM_eAVQQkxBrP-oM: Timeout'}, u'type': u'http-01'}
```